@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun May 24 13:28:52 +0700 2026
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_accelerator_top_behav -key {Behavioral:sim_1:Functional:tb_accelerator_top} -tclbatch tb_accelerator_top.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_48ac.protoinst" -protoinst "protoinst_files/bd_886d.protoinst" -protoinst "protoinst_files/bd_892d.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
call xsim  tb_accelerator_top_behav -key {Behavioral:sim_1:Functional:tb_accelerator_top} -tclbatch tb_accelerator_top.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_48ac.protoinst" -protoinst "protoinst_files/bd_886d.protoinst" -protoinst "protoinst_files/bd_892d.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
